package ftok

import (
	"crypto/sha1"
	"encoding/hex"
	"path/filepath"
)

// Sha1 - return sha1 hex string generated by path.
// dir(path) have to exist.
func Sha1(path string) (hash string, err error) {
	base := filepath.Base(path)
	if hash, err = filepath.Abs(filepath.Dir(path)); err != nil {
		return "", err
	}
	if hash, err = filepath.EvalSymlinks(hash); err != nil {
		return "", err
	}
	sha := sha1.Sum([]byte(filepath.Join(hash, base)))
	return hex.EncodeToString(sha[:]), nil
}
